In [1]:
#import libraries
import numpy as np
import torch

In [2]:
#create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

print(A)

[[ 0.48706246 -1.25222503 -1.77562893 -0.13143465]
 [ 0.3432118   0.07341473  0.74364516  1.39114941]
 [-0.79925636  1.80334324  0.09674946 -1.5616626 ]]


Using Pytorch

In [2]:
# create some random matrices
A = torch.randn(3,4)
print(A)

tensor([[ 0.0161,  0.7229,  1.4164,  0.0915],
        [-1.6002, -0.0967, -0.8297,  2.1558],
        [ 0.5111,  1.1486,  0.7501, -0.3084]])
