In [1]:
#import libraries
import numpy as np
import torch

In [3]:
#create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

print(A)

[[-0.51188494 -0.7805363   0.21432569  0.44657432]
 [ 0.13781453  0.0190868   0.97864048 -0.07601848]
 [-0.6413379   0.3306318   0.65453665  0.69552338]]


Using Pytorch

In [2]:
# create some random matrices
A = torch.randn(3,4)
print(A)

tensor([[-0.3934,  1.4183, -0.0402,  0.0805],
        [ 0.4219,  0.1104, -0.6350, -0.1215],
        [-0.0839, -0.1292,  2.2675, -1.4865]])
